*WELCOME*


In [1]:
import numpy as np

In [11]:
arr= np.array([[4,5,6,3]], np.int8)

In [17]:
arr

array([[4, 5, 1, 3]], dtype=int8)

In [16]:
arr[0,2]=1

In [14]:
arr.shape

(1, 4)

In [15]:
arr.dtype

dtype('int8')

#conversion from other python structure

In [18]:
lsarray = np.array ([[1,2,3], [4,5,6], [7,8,9]])

In [25]:
lsarray

array([[1, 0, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
lsarray.size

9

In [21]:
lsarray.shape

(3, 3)

In [22]:
lsarray.dtype

dtype('int32')

In [24]:
lsarray[0,1]=0

In [30]:
zeros =np.zeros((2,3))

In [33]:
zeros.shape

(2, 3)

In [36]:
k=np.arange(10)

In [37]:
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
lspace = np.linspace(1,20,6)

In [39]:
lspace

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [41]:
emp = np.empty((4,6))

In [42]:
emp

array([[3.69763192e-292, 1.86918699e-306, 1.69121096e-306,
        1.86919378e-306, 4.45064851e-308, 1.20161730e-306],
       [7.56587585e-307, 7.56593017e-307, 1.24610383e-306,
        1.24610723e-306, 1.37962320e-306, 1.29060871e-306],
       [2.22522597e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 1.00132653e-307, 8.01097889e-307],
       [1.69119873e-306, 1.11261570e-306, 1.95818994e-306,
        1.11261502e-306, 1.42410974e-306, 5.97819431e-322]])

In [43]:
empl = np.empty_like(lspace)

In [44]:
empl

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [48]:
arr=np.arange(22)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [50]:
    arr = arr.reshape(2,11)

In [51]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [57]:
arr=arr.ravel()

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [60]:
arr.shape

(22,)

In [1]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [4]:
arr = np.array(x)

In [3]:
import numpy as np

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr.sum(axis=0)

array([12, 15, 18])

In [12]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [13]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
arr.flat

In [18]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [19]:
arr.ndim

2

In [20]:
arr.size

9

In [21]:
arr.nbytes

36

In [22]:
one = np.array([1,2,3,4])

In [23]:
one.argmax()

3

In [25]:
one.argsort()

array([0, 1, 2, 3], dtype=int32)

In [26]:
one.argmin()

0

In [27]:
arr.argmin()

0

In [28]:
arr.argmax()

8

In [2]:
arr.ravel()

NameError: name 'arr' is not defined

In [6]:
ar2 = np.array([[4, 1, 7],
       [2, 5, 8],
       [12, 2, 9]])

In [5]:
import numpy as np

In [7]:
ar = np.array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
ar2 + ar

array([[ 5,  5, 14],
       [ 4, 10, 16],
       [15,  8, 18]])

In [9]:
ar * ar2

array([[ 4,  4, 49],
       [ 4, 25, 64],
       [36, 12, 81]])

In [10]:
ar - ar2

array([[-3,  3,  0],
       [ 0,  0,  0],
       [-9,  4,  0]])

In [11]:
np.sqrt(ar2)

array([[2.        , 1.        , 2.64575131],
       [1.41421356, 2.23606798, 2.82842712],
       [3.46410162, 1.41421356, 3.        ]])

In [12]:
ar2.sum()


50

In [13]:
ar2.min()

1

In [14]:
ar


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
np.where(ar>5)

(array([0, 1, 2, 2], dtype=int32), array([2, 2, 1, 2], dtype=int32))

In [16]:
np.count_nonzero(ar)

9

In [17]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32))

In [18]:
import sys

In [19]:
py_ar = [0,4,55,2]

In [20]:
np_ar = np.array(py_ar)

In [21]:
sys.getsizeof(1) * len(py_ar)

56

In [22]:
np_ar.itemsize * np_ar.size

16